use-haskell:
  image: use-haskell
  environment:
    # The start of active environment variables. Set as needed.
    - MONGODB_IP=database
    # - MONGODB_PORT
    # - MONGODB_DATABASE=USE_HASKELL_DB
    - LOG_LEVEL=DEBUG
    # - https_proxy=http://www-proxy.scss.tcd.ie:8080
    # - http_proxy=http://www-proxy.scss.tcd.ie:8080
  command: /usr/local/bin/use-haskell-exe
  ports:
    - "4000"
  links:
    - database
database:
  image: mongo:3.0.2
  ports:
    - "25017:25017"
